version: "3"

networks:
  lightlogs:
    driver: bridge

services:
  app:
    build:
      args:
        user: default
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - lightlogs

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lightlogs

  timescale:
    image: timescale/timescaledb:latest-pg12
    container_name: timescale
    restart: unless-stopped
    tty: true
    ports: 
        - "5432:5432"
    environment: 
        POSTGRES_DB: lightlogs
        POSTGRES_USER: default
        POSTGRES_PASSWORD: secret
    networks: 
        - lightlogs
